name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.18

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==2.1.4
        poetry install

    - name: Configure AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "AWS credentials configured."

    - name: Pull Data with DVC
      run: dvc pull

    - name: Run tests
      run: poetry run pytest


  deploy:
    name: Deploy to Render
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Render Deployment
      run: |
        curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"clearCache": true}' \
          https://api.render.com/v1/services/srv-d2uuih7fte5s73bj5lb0/deploys
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
